theme: minima
title: Victor's Website and Blog
author: Victor Choi
email: victor_choi@berkeley.edu
description: > # this means to ignore newlines until "baseurl:"
  Welcome! My name is Victor Choi. 
  I will write about topics that I am interested in on this website.
  Feel free to look around!

# social links
github_username:  vdchoi # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
