#-------------------------------
# General Site Settings

title: Victor Choi | Website and Blog
description: Welcome to my personal website and blog. I enjoy writing about interesting topics in applied statistics. Feel free to take a look around! # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# About Section
author-name:   Victor Choi
author-avatar: vikkyc.png


#-------------------------------
# Contact links
linkedin:  https://www.linkedin.com/in/vdchoi/ # Add your Facebook handle
github: https://github.com/vdchoi/    # Add your Facebook handle
instagram:  # Add your Facebook handle
pinterest:  # Add your Facebook handle


#-------------------------------
# Comment Section (Disqus)
#disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 7
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
