# Site
name: "Victor Choi"
title: "Welcome to my Personal Website"
description: "I enjoy writing about applied statistics. Feel free to take a look around!"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  victor:
    name: Victor Choi
    display_name: Victor
    github: https://github.com/vdchoi
    gravatar: 7b2f6355e53ed29a4f377ade178aaa8a
    linkedin: https://www.linkedin.com/in/vdchoi/
    description: "Hi! My name is Victor Choi. I work as a Senior Product Analyst at TrueCar, responsible for product analytics and experimentation on our Marketplace and Growth product teams."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
